### ISSUE TITLE
Report errors when too many arguments in a let

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#101]
I didn't find an error like this:
```
(let ((x \ a b)) ;;should have been (x \ (- a b))
  …)
```
I just got wrong results
so this should report errors.

**Comment by tomhrr** [comment]
On Thu, Sep 15, 2016 at 06:53:56AM -0700, Fabio Krapohl wrote:
> I didn't find an error like this:
>
> (let ((x \ a b))
>   …)
> 
> I just got wrong results
> so this should report errors.

Thanks, this has been fixed.
