### ISSUE TITLE
Bugs with no-op

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#102]
```
(def main (fn extern-c void (void)
  (using-namespace std
    (no-op)
    (def x (var auto \ 1)))
  (def z (var auto \ x))))
```
x not in scope for z

**Comment by tomhrr** [comment]
On Thu, Sep 15, 2016 at 04:27:49PM -0700, Fabio Krapohl wrote:
> (def main (fn extern-c void (void)
>   (using-namespace std
>     (no-op)
>     (def x (var auto \ 1)))
>   (def z (var auto \ x))))
>
> x not in scope for z

Thanks, this has been fixed.
