### ISSUE TITLE
Initializing function-pointers at compile-time not possible

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#103]
Example:
```
(def fun (fn intern void (void)
  (return)))

(def fun-ptr (var intern (p (fn void (void))) (# fun))) ;;segfault here
```

**Comment by tomhrr** [comment]
On Fri, Sep 16, 2016 at 08:58:17AM -0700, Fabio Krapohl wrote:
> Example:
>
> (def fun (fn intern void (void)
>   (return)))
> 
> (def fun-ptr (var intern (p (fn void (void))) (# fun))) ;;segfault here

Thanks, this has been fixed.
