### ISSUE TITLE
Add debug macros

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#110]
Especially the current way to see macroexpansions is not very usable.
I'd like to be able to get the macro-expansion of a macro at compiletime, so I could write something like:
`(print (macro-expansion (my-macro …)))` and see the expanded macro, maybe being able to specify a number of maximal expansions for recursive macros

**Comment by tomhrr** [comment]
Thanks for this.  `eval-macro-call` was added for unrelated reasons after this issue was submitted, and it handles the `macroexpand` case.  It only had to be modified slightly to handle the `macroexpand-1` case, fortunately.
