### ISSUE TITLE
I can't use forms inside uq, but have to create a temporary variable

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#140]
```
(import macros)

(using-namespace std.macros
  (def test (macro intern (void)
    (qq identity (uq (mnfv mc 1))))))

(def main (fn extern-c void (void)
  (printf "%i\n" (test)))) 
```

`(test)` expands to `(identity (mnfv mc 1))` instead of `(identity 1)`

**Comment by porky11** [comment]
Similar problem with uql:
`(qq (uql (fun arg)))` will expand correctly, but `fun` is called twice, which leads to problems in some cases.

**Comment by tomhrr** [comment]
Thanks, these problems have now been fixed.
