### ISSUE TITLE
Allow lists to be empty

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#141]
Is useful for writing macros and using them.
Currently, I would have to use a special value as list argument (like void for no-argument-functions), or a list-prefix (like `(array …)` `(refines …)`)
it is more clear, that something is empty / has no arguments, if `()` is used, and also easier to parse.
`()` could expand to a empty DNode.
I don't think, the core forms will have to use `()`, but my own parsing macros should be able to read `()`.
This way, defining large objects using array-like data types won't need a prefix or empty special value.

**Comment by tomhrr** [comment]
Thanks, this has been done.  There may still be some code that assumes a true value for `is-list` means that `list-node` will be set, though.
