### ISSUE TITLE
CMake uses wrong flags for arch linux

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#164]
In arch linux, libtinfo is not available, but libncurses is. The test at following line may be wrong

https://github.com/tomhrr/dale/blob/a738372ac080f29c9762007a3ea049b6d9e0e94f/CMakeLists.txt#L145

**Comment by tomhrr** [comment]
This should now be fixed.  I hadn't realised that between 3.4 and 3.5, part of the output of `llvm-config --ldflags` had moved to the output of the new `--system-libs` flag.  CMakeLists.txt now handles this correctly.
