### ISSUE TITLE
Parsing header files containing undefined functions

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#178]
When a c library doesn't contain all functions, that are declared in the headef file, it is no problem, if they are declared in dale as extern-c anyway.
But if I define a wrapper around this undefined function, it won't compile anymore, because the function is not defined.
```
(import stdlib)

(def x (fn extern-c void (void))) ;;unused undeclared function

(def X (fn (attr inline) extern void (void) ;;wrapper function, without this, the program works
  (x)))

(def main (fn extern-c void (void)
  (printf "no problem\n")))
```

**Comment by tomhrr** [comment]
This is intentional, and C has analogous behaviour.  When `x` is unused, it doesn't matter that there isn't a definition for it, but once it is used, it must be defined, even if the use site itself is not used.
