### ISSUE TITLE
Dale does not build on OSX

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#180]
So instead of spamming #41 I figured this should be its own open issue.

I am unable to compile Dale on OSX. All LLVM versions I've tried give me this error:

```
[ 77%] Generating libcstdio.so
Assertion failed: (Ty->isPointerTy() && "Illegal argument for getIndexedOffset()"), function getIndexedOffset, file DataLayout.cpp, line 642.
make[2]: *** [libcstdio.so] Abort trap: 6
```

I've tried LLVM 3.5.2, 3.5.1, 3.5, 3.4 (probably one of 3.4.2 and 3.4.1, lost track). LLVM lower than 3.4 itself doesn't build so don't know if they have this issue.

This is on OSX 10.12.3 with XCode 8.3

**Comment by tomhrr** [comment]
The offsetof problem can be replicated on Linux (current Debian Testing) with a debug build of LLVM 3.5.2, and has now been fixed.  It should now build, but there are still problems with some of the tests.  These should be fixed within the next few days.  Using a release build of LLVM is another alternative, in the interim.

**Comment by tomhrr** [comment]
This should be OK now, but I don't have an OS X machine for testing.  Please reopen if there are still problems.
