### ISSUE TITLE
Any plans for a REPL?

### ISSUE THREAD

**Issue by spacepluk** [tomhrr/dale#192]

**Comment by porky11** [comment]
It's already possible to write something like a REPL by using the evaluation function in a macro, that evaluates a form read from user and expands to this macro again.
(not sure how I did it exactly, I may post it if you want, maybe I posted it somewhere different)

**Comment by tomhrr** [comment]
Thanks for this.  There weren't any plans as such, but it's a good idea and was fairly simple to implement, not that it's particularly full-featured compared with some.  See https://github.com/tomhrr/dale/blob/master/doc/1-12-repl.md for details.
