### ISSUE TITLE
Confusing semantics of (var extern type)

### ISSUE THREAD

**Issue by ChengCat** [tomhrr/dale#203]
```
(import cstdio)
(def x (var extern int))
(def main (fn extern-c int (void)
  (printf "%d\n" x)
  0))
```

I expect `x` is defined in this module with an uninitialized value. But the compiler complains about missing symbols instead.
```
undefined reference to `x'
```

I expect `extern` variables have the same semantics with `extern` structs and functions, i.e. defined in the module and visible to other modules.

**Comment by tomhrr** [comment]
Thanks for this.  There wasn't documentation for this (now updated), but the semantics here are intentionally the same as in C:

    $ cat test.c
    #include "stdio.h"
 
    extern int x;
 
    int main(void)
    {
        printf("%d\n", x);
        return 0;
    }
    $ cc test.c
    /usr/bin/ld: /tmp/ccUQRZFe.o: in function `main':
    test.c:(.text+0x6): undefined reference to `x'
    collect2: error: ld returned 1 exit status

**Comment by tomhrr** [comment]
The C consistency is mainly to limit surprise for people who are used to C, and to allow people to use C-like approaches to things if that's what they'd prefer.  There are some exceptions to this, like the general lack of implicit casting, but it's mostly very similar.  I think the arguments in favour of C consistency here are compelling:

 - function declarations work in the same way: if it's not defined elsewhere, then the function cannot be used; and
 - providing an explicit definition for the `extern`-scoped variable is typically straightforward.

**Comment by ChengCat** [comment]
> The C consistency is mainly to limit surprise for people who are used to C, and to allow people to use C-like approaches to things if that's what they'd prefer.

I think this sentence expresses your intention very well, and now I can understand it.

I have been always finding the various kinds of linkage of Dale confusing. I am going to use Dale more, and to give this issue more thought.
