### ISSUE TITLE
Doesn't Build on Apple Silicon

### ISSUE THREAD

**Issue by BracketMaster** [tomhrr/dale#212]
I attempted a build and encountered: 
```bash
Unable to create execution engine: No available targets are compatible with triple "aarch64-apple-darwin20.5.0"
make[2]: *** [libarithmetic.so] Abort trap: 6
make[1]: *** [CMakeFiles/arithmetic.dir/all] Error 2
make: *** [all] Error 2
```
Can I disable libarithmetic somehow?

**Comment by tomhrr** [comment]
Thanks for this report.

> Can I disable libarithmetic somehow?

The problem doesn't appear to be specific to libarithmetic, unfortunately.

I'm not sure why the target issue is happening, but even if it weren't, there are parts of the code that assume either an x86 or x86-64 platform, so it may be that it doesn't work properly on ARM anyway.  I'll see about having a more in-depth look at this over the next week or so.

**Comment by BracketMaster** [comment]
Yeah, it'd be great to get Dale working on Raspberry Pi and friends. I really like the Dale language.
