### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tomhrr/dale#29]
Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "open a stream") ⇒ [copyFile](https://github.com/tomhrr/dale/blob/19fb085d2fb68618bc14723ceeb187b29fc5dcfe/src/dale/dalec.cpp#L62)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "memory allocation") ⇒ [Node::toDNode](https://github.com/tomhrr/dale/blob/a4274332841c89056f3de0e0de6e79c69f0a1c72/src/dale/Node/Node.cpp#L147)

**Comment by tomhrr** [comment]
Thanks, this has been fixed.

**Comment by elfring** [comment]
Are there a few update candidates left over around function calls like the following?
* fclose
* fflush
* fseek

**Comment by tomhrr** [comment]
Thanks, those have been fixed now too.

**Comment by elfring** [comment]
Thanks for your source code improvement.
