### ISSUE TITLE
Dale is difficult to find

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#31]
And this is an issue! Dale seems like a pretty nice programming language if you ask me. I was wondering why I haven't found this before, because I've definitely searched for it... A lot. I just found Dale because someone in the racket irc linked to it. I think dale needs some basic website or something with a domain name. You could just use github pages for hosting so that it's not very costly to get a website. Perhaps it would be nice to start an irc channel as well. Although, perhaps you aren't interesting in building a community for dale, I could understand if that's the case.

Cheers :)

**Comment by tomhrr** [comment]
Done, to some extent :).  See http://dale-lang.org and https://groups.google.com/forum/#!forum/dale-lang.

**Comment by BitPuffin** [comment]
Fantastic!

**Comment by porky11** [comment]
it's still difficult to find.
I just found it by accident when searching for lisplike languages on reddit.
first I even found another interesting lisp made for graphics and sound programming, but this is more what I want, I even thought about creating something like this (also using llvm) myself before
