### ISSUE TITLE
def for types?

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#32]
Hey I was wondering if there is a way or will be a way to use something like def to make a new type based on some other one:

``` dale
(def Identifier int)

(def jobject (p void))

(def string (const (p char)))
``` 

Do you have to do some kind of macro voodoo right now or is there already some way. I wonder if maybe concepts is what I want but I'm not sure what they do or how to use them yet, the docs were a bit unclear about it.

Thanks!

**Comment by tomhrr** [comment]
There's no built-in way to do this, so the options with the current core are using a plain macro (for typedef-esque behaviour) or a struct wrapper around the type (for a new type).  Concepts will help here, but only insofar as they can ensure that the argument form is a type.  I'll put together some better examples of this within the next couple of days.

**Comment by BitPuffin** [comment]
I suppose the best way to get a full new type would be to use compiler introspection and get all the fields for a struct type etc if that's the passed arguments.

I'm not quite sure how to use a macro for typedef-esque behaviour though. But I haven't quite groked how macros work in Dale at all yet so I guess I'll get there at some point. Some examples would surely help!

**Comment by BitPuffin** [comment]
Ah I think I figured it out. You can do something like this

``` dale
(import macros)
(using namespace std.macros
(def string (macro extern ()
  (qq p (const char)))))

(def some-string (var intern (string) "hello"))
```

Kind of a shame that you have to add an extra set of parenthesis but I suppose I can live with that.

**Comment by tomhrr** [comment]
There are now some examples of typedef-like macros in eg/def-type/def-type.dt.  The first is as per your previous comment.  The second creates a struct wrapper around the previous type, and includes a macro that creates wrappers for functions that use the original type.
