### ISSUE TITLE
Segmentation Fault with invalid type name

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#34]
With this code, which mis-spells ```DNode``` to ```DNODE```:

``` dale
(def foo (macro extern ((name (p char)) (t DNODE))))
```

When attempting to compile, it segfaults:

``` zsh
% dalec foo.dt
zsh: segmentation fault  dalec foo.dt
```

However once I was able to give the correct error message randomly:

``` zsh
% dalec foo.dt -vv
dalec: invalid option -- v
dalec: invalid option -- v
foo.dt:1:44: error: type not in scope: 'DNODE'
```

Other times with the same (invalid) command line options not so much:

``` zsh
% dalec foo.dt -vv
dalec: invalid option -- v
dalec: invalid option -- v
zsh: segmentation fault  dalec foo.dt -vv
```

So I think this is probably uninitialized memory that is sometimes 0 and sometimes just garbage. Should be fairly easy to find using the sanitizers in llvm since the compiler is written in C++.

**Comment by tomhrr** [comment]
Thanks for the bug report, it turned out to be right on the money.

**Comment by BitPuffin** [comment]
Great! Thanks for fixing it. Would hate to debug a larger codebase with "Segmentation fault" as my only error message :)
