### ISSUE TITLE
Segmentation fault with macros

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#35]
I'm not sure what I'm doing wrong but I'm getting another segmentation fault. On OSX. Here is the code:

``` dale
(import macros)

(using-namespace std.macros
  (def def-type-alias (macro extern (new old)
    (qq def (uq new) (macro extern ()
      old)))))
```

``` zsh
% dalec def-type-alias.dt
zsh: segmentation fault  dalec def-type-alias.dt
```

**Comment by tomhrr** [comment]
If a macro doesn't take parameters, it should have '(void)', rather than
'()', as its parameter list.  The error message could be better, though. :)

**Comment by BitPuffin** [comment]
Ah!

Yeah I realized that my code was wrong, but the bug report was mainly because of the segmentation fault :dancer: Trying to figure out how to build dale with sanitizers, thought it was just CXXFLAGS="-g -fsanitize=address" make. But it seems to have made no difference. Could also be that address is the wrong sanitizer for this error though.

I'll give void a try though!
