### ISSUE TITLE
Build Error: <unknown>:232:14: error: not in scope: 'get-dnodes' (see macro at 93:5) 

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#39]
This is on osx, if that's relevant:

```zsh
% make
[ 75%] Built target dalec
[ 75%] Built target drt
[ 76%] Built target cstdio-core
[ 77%] Built target macros-core
[ 78%] Built target introspection
[ 79%] Built target stdlib
[ 79%] Built target macros
[ 79%] Built target unistd
[ 79%] Built target cstring
[ 80%] Built target cstdlib
[ 80%] Built target cstdio-arch
[ 81%] Built target cstdio
[ 82%] Generating libassert.so
<unknown>:232:14: error: not in scope: 'get-dnodes' (see macro at 93:5)
make[2]: *** [libassert.so] Error 1
make[1]: *** [CMakeFiles/assert.dir/all] Error 2
make: *** [all] Error 2
```
This makes it so that dale is not buildable on the latest version. The odd thing is that I did not find any get-dnodes when doing this:

```zsh
% find . -exec grep "get-dnode" {} \; 2>/dev/null
```

**Comment by tomhrr** [comment]
Try removing all files beginning with 'lib', and rebuilding. It's probably
happening because libmacros has been built referring to get-dnodes, and not
rebuilt after get-dnodes was removed.

**Comment by BitPuffin** [comment]
Oh yeah you are right. It was because it was finding libraries in by lib/dale directory. Sorry :)

Cheers
