### ISSUE TITLE
Move semantics?

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#43]
I was just thinking about how it could be useful to have rvalue overloading and move semantics in this language so that unique_ptr from C++ could be implemented. I know that there's shared-ptr in this language but reference counting has some undesirable overhead at times :)

**Comment by tomhrr** [comment]
I think this is a good idea, and should be able to implement something
along the lines of what's in C++ without too much trouble.  (Roughly:
an additional rv-ref parameter type, move-copy and move-assign
operations, a way to specify that certain copy/assign operations
aren't permitted for a given type, and possible subsuming of retvals
within the rv-ref concept.)

**Comment by tomhrr** [comment]
Done, except that retvals have been left alone, since there's no compelling reason to change them.  This work helped to tidy up the internals around copying quite a bit, too, so thanks for the suggestion.

**Comment by BitPuffin** [comment]
That's cool that you implemented it. I will probably give it a spin soon!
