### ISSUE TITLE
Simplify usage of enums

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#57]
Enums have to be assigned to variables, before they are used
when i have a enum `(def T (enum intern uint (a b c)))` and a function `(def f (fn intern void ((x T))))` I don't want to write something like this:
```
(def x (var auto T (| a b)))
(f x)
```
I'd prefer something like this:
```
(f (using-namespace T (| a b))
```
Edit: not even the first example works, so enums aren't really usable

**Comment by tomhrr** [comment]
On Sat, Aug 27, 2016 at 03:58:21AM -0700, Fabio Krapohl wrote:
> Enums have to be assigned to variables, before they are used
> when i have a enum `(def T (enum intern uint (a b c)))` and a function `(def f (fn intern void ((x T))))` I don't want to write something like this:
>
> (def x (var auto T (| a b)))
> (f x)
> 
> I'd prefer something like this:
> 
> (f (using-namespace T (| a b))

Enum values take the form ({name} {member-name}):

    (import cstdio)
    
    (def T (enum intern int (a b c)))
    
    (def f (fn intern void ((t T))
      (printf "%d\n" t)
      (return)))
    
    (def main (fn extern-c int (void)
      (def x (var auto T (| (T a) (T b))))
      (f x)
      (f (| (T a) (T b)))
      0))

The documentation on this point is not terribly clear, so it's been
updated with an example.

**Comment by porky11** [comment]
it would be nice anyway if I could write `(T (| a b))` instead of `(| (T a) (T b))`
then all variable names would be of type T
some additional macro would be useful to allow some other variables than the enum's members, similar to the unquote macro

**Comment by tomhrr** [comment]
On Sun, Aug 28, 2016 at 06:13:16PM -0700, Fabio Krapohl wrote:
> it would be nice anyway if I could write `(T (| a b))` instead of `(| (T a) (T b))`
> then all variable names would be of type T

Fair enough, this has been added.

> some additional macro would be useful to allow some other variables than the enum's members, similar to the unquote macro

Do you mean similarly to how prime-function works in stdlib, where the
second argument is cast to match the type of the first?

**Comment by porky11** [comment]
Example:
```
(def a (enum intern (x y …)))

(def x (var auto a y))
(def z (var auto a (| x …))
```
what if x means the variable x, not the enum x?
let's add some form similar to uq (called `unenum` here):
```
(def z (var auto a (| (unenum x) …)))
```

**Comment by tomhrr** [comment]
On Tue, Sep 06, 2016 at 12:43:13AM -0700, Fabio Krapohl wrote:
> Example:
>
> (def a (enum intern (x y …)))
> 
> (def x (var auto a y))
> (def z (var auto a (| x …))
>
> what if x means the variable x, not the enum x?
> let's add some form similar to uq (called 'unenum' here):
>
> (def z (var auto a (| (unenum x) …)))

Thanks, I see what you mean now.  To fix the main problem here, a
const variable for each enum element is introduced at the same time as
the enum itself.  This means that in the above example, the definition
of 'x' as a var will fail with an error about 'x' already being
defined in that scope.
