### ISSUE TITLE
Bug: Definition-order matters

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#58]
This works:
```
(def x (fn intern int ((a int)) a))
(def x (macro intern (a) a))
```
This doesn't work
```
(def x (macro intern (a) a))
(def x (fn intern int ((a int)) a))
```

**Comment by tomhrr** [comment]
Thanks, this has now been fixed.

**Comment by porky11** [comment]
You fixed it the wrong way :)
now both don't work, but I'd prefer if both work, so overloading a macro would be similar to specializing c++ templates.

**Comment by tomhrr** [comment]
Ugh, indeed :(.  I'll fix this properly soon.

**Comment by tomhrr** [comment]
Fixed, correctly this time.

**Comment by porky11** [comment]
I found some example, where this still causes problems, see following
https://github.com/porky11/dale-extensions/blob/master/src/util.dt#L80
defc-multi (this helps for defining a single overloaded function for multiple extern-c functions, documentation may be added later, but isn't important anyway)
if the version with 3 arguments and rest is defined first, it will produce endless-loop printing some error message, if the version with 2 arguments is defined first, it won't work when called with 3 arguments
