### ISSUE TITLE
Suggestion for extending `or` and maybe `and`

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#61]
in common lisp it is useful, that or returns the last true value of a function, so one can say `(setq x (or (f1) (f2) (f3)))`. Because dale is statical typed, it will need one extra-function that checks if a value is true, so or should expand to something like this:
```
(let ((result1 \ (f1)))
  (if (is-valid result1)
    result1
    (let ((result2 \ (f2)))
      (if (is-valid result2)
        result2
        (f3)))))
```
`is-valid` would only return false for false bool-values, for nullpointers, for Maybe-objects that are None, for emty lists etc
(not sure if this shuld be in the core or rather in an extern lib)

**Comment by tomhrr** [comment]
On Sat, Aug 27, 2016 at 01:34:30PM -0700, Fabio Krapohl wrote:
> ...

I think this is a reasonable idea, though a module implementation
seems like the way to go, given that there doesn't appear to be any
compelling reason to put it in the core.

**Comment by porky11** [comment]
Implemented
