### ISSUE TITLE
Add bitshift enums

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#63]
there are many macros where each means a single set bit, so it would be useful that enums are not only able to count but also bitshift, so that
```
(def test (enum intern bitshift (a b c))
(def test2 (enum intern bitshift ((a 0x08) b c))
```
would be the same as
```
(def test (enum intern add ((a 0x01) (b 0x02) (c 0x04))))
(def test2 (enum intern add ((a 0x08) (b 0x10) (c 0x20))))
```
(`add` and `bitshift` are additional qualifiers for the enum, the version with `add` acts like the existing enum)

**Comment by tomhrr** [comment]
On Sun, Aug 28, 2016 at 06:26:03PM -0700, Fabio Krapohl wrote:
> there are many macros where each means a single set bit, so it would be useful that enums are not only able to count but also bitshift, so that
>
> (def test (enum intern bitshift (a b c))
> (def test2 (enum intern bitshift ((a 0x08) b c))
> 
> would be the same as
> 
> (def test (enum intern add ((a 0x01) (b 0x02) (c 0x04))))
> (def test2 (enum intern add ((a 0x08) (b 0x10) (c 0x20))))
> 
> ('add' and 'bitshift' are additional qualifiers for the enum, the version with 'add' acts like the normal enum)

Thanks for this.  I ended up implementing it in a library, rather
than as an extension to the language proper, but apart from some minor
syntactical differences it's as per what you have above:
 
    user@host:~$ cat test.dt
    (import cstdio)
    (import bitset-enum)
    
    (def-bitset-enum myenum intern int ((a 2) b (c 0x10) d))
    
    (def main (fn extern-c int (void)
      (printf "%d\n" (myenum a))
      (printf "%d\n" (myenum b))
      (printf "%d\n" (myenum c))
      (printf "%d\n" (myenum d))
      0))
    user@host:~$ dalec test.dt
    user@host:~$ ./a.out
    2
    4
    16
    32
    user@host:~$
