### ISSUE TITLE
More things should be able to be overloaded

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#66]
It even was possible in a earlier version I used.
I like to overload lenght for functions that take a fixed number of arguments
```
(def a (fn ((x X) (y Y))))
(def a (macro ((x X) (y Y) ...)) ; (a x y1 y2 y3) will expand to (do (x y1) (x y2) (x y3))
```

**Comment by tomhrr** [comment]
On Wed, Aug 31, 2016 at 07:01:11AM -0700, Fabio Krapohl wrote:
> It even was possible in a earlier version I used.
> I like to overload lenght for functions that take a fixed number of arguments

This is working OK for me at the moment, so I'm pretty sure it's been
fixed in the interim, but will wait for your confirmation.

**Comment by porky11** [comment]
My macro still does not work, but this is another problem,
