### ISSUE TITLE
include should (be able to) load files as a relative part

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#67]
It is useful when i don't want to write a big module into a single file.

**Comment by tomhrr** [comment]
On Wed, Aug 31, 2016 at 07:06:36AM -0700, Fabio Krapohl wrote:
> It is useful when i don't want to write a big module into a single file.

This should be possible already via the "include" form:

    user@host:~$ cat mymod.dt
    (module mymod)
    
    (include "part1.dt")
    (include "part2.dt")
    user@host:~$ cat part1.dt
    (def n (var extern int 10))
    user@host:~$ cat part2.dt
    (def m (var extern int 25))
    user@host:~$ ./dalec -I. -c mymod.dt
    user@host:~$ cat test.dt
    (import mymod)
    (import cstdio)
    
    (def main (fn extern-c int (void)
      (printf "%d %d\n" n m)
      0))
    user@host:~$ ./dalec test.dt
    user@host:~$ ./a.out
    10 25
    user@host:~$

**Comment by porky11** [comment]
I get errors like this:
`test5.dt:2:10: error: /usr/local/include/dale/part1.dt: No such file or directory`
It doesn't search in the local directory but in the dale directory.

**Comment by tomhrr** [comment]
On Sat, Sep 10, 2016 at 06:42:19AM -0700, Fabio Krapohl wrote:
> I get errors like this:
> `test5.dt:2:10: error: /usr/local/include/dale/part1.dt: No such file or directory`
> It doesn't search in the local directory but in the dale directory.

'.' is not an include directory by default, so it has to be specified
explicitly by way of the -I flag.

**Comment by porky11** [comment]
I thought include is just like adding the content of the specified file into the current file, but it works like import, and only imports extern symbols

**Comment by tomhrr** [comment]
On Tue, Sep 13, 2016 at 02:19:28AM -0700, Fabio Krapohl wrote:
> I thought include is just like adding the content of the specified file into the current file, but it works like import, and only imports extern symbols

Thanks, this has been fixed.
