### ISSUE TITLE
for loop pretty useless

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#69]
only difference to while is the init-form, which doesn't even create a new variable, but only set it. Normally you would set the variable already when defining it.
I would suggest deleting this version of for and adding a loop that expands to something using iterators (I'll write the macro when I need it)

**Comment by porky11** [comment]
it would also be nice if the for-loop can create multiple variables in the init-form
you would write this
```
(for ((i \ 0) (a \ (begin …)) …) cond (do (incv i) …)
  …)
```

**Comment by tomhrr** [comment]
On Sun, Sep 11, 2016 at 01:32:45AM -0700, Fabio Krapohl wrote:
> it would also be nice if the for-loop can create multiple variables in the init-form
> you would write this
>
> (for ((i \ 0) (a \ (begin …)) …) cond (do (incv i) …)
>   …)

This has now been added:

    (import stdlib)
    
    (def main (fn extern-c int (void)
      (for ((i \ 0) (j \ 0))
           (and (< i 5) (< j 5))
           (do (incv i) (incv j))
        (printf "%d %d\n" i j))
      0))

yields:

    0 0
    1 1
    2 2
    3 3
    4 4

**Comment by porky11** [comment]
I implemented a loop using iterators.
```
(using-namespace std.macros
(def in (macro extern (name value ...)
  (let ((en \ (make-gensym-var-node mc))
        (bn \ (make-gensym-var-node mc))
        (val \ (make-gensym-var-node mc)))
    (qq for ( #| ((uq val) \ (move (uq value))) |# ((uq bn) \ (begin (uq value))) ((uq en) \ (end (uq value))))
            (< (uq bn) (uq en))
            (setv (uq bn) (successor (uq bn)))
      (let (((uq name) \ (source (uq bn))))
        (uql (get-varargs-list (- (arg-count mc) 2))))))))
)
```
I don't know, how to fix, that value is evaluated twice, so that it works as well for lvalues as for rvalues

**Comment by tomhrr** [comment]
On Tue, Sep 13, 2016 at 07:37:39AM -0700, Fabio Krapohl wrote:
> I implemented a loop using iterators.
>
> (using-namespace std.macros
> (def in (macro extern (name value ...)
>   (let ((en \ (make-gensym-var-node mc))
>         (bn \ (make-gensym-var-node mc))
>         (val \ (make-gensym-var-node mc)))
>     (qq for ( #| ((uq val) \ (move (uq value))) |# ((uq bn) \ (begin (uq value))) ((uq en) \ (end (uq value))))
>             (< (uq bn) (uq en))
>             (setv (uq bn) (successor (uq bn)))
>       (let (((uq name) \ (source (uq bn))))
>         (uql (get-varargs-list (- (arg-count mc) 2))))))))
> )
> 
> I don't know, how to fix, that value is evaluated twice, so that it works as well for lvalues as for rvalues

Thanks, an 'is-lvalue' form has been added to the introspection module
to support this sort of macro.

**Comment by porky11** [comment]
Should I use the current version for rvalues and create a tmp-val for lvalues?

**Comment by tomhrr** [comment]
On Sat, Sep 17, 2016 at 04:27:00PM -0700, Fabio Krapohl wrote:
> Should I use the current version for rvalues and create a tmp-val for lvalues?

I think it's the inverse of that: the temporary value is necessary for
the rvalue form, but not the lvalue form.

**Comment by porky11** [comment]
oh yes, that's what I meant, I just confused lvalues and rvalues, (am not used to them, because I mainly used CL)

**Comment by porky11** [comment]
my current version of `in` causes segfaults, but I don't know why
```
(def in (macro extern (name value ...)
  (let ((en \ (make-gensym-var-node mc))
        (bn \ (make-gensym-var-node mc))
        (val \ (if (is-lvalue mc value) value (make-gensym-var-node mc)))
        (uql-on-empty-list-does-not-work \ (make-gensym-var-node mc)))
    (qq for ((uql (if (is-lvalue mc val) (qq (uq uql-on-empty-list-does-not-work) \ true)
                                            (qq (uq val) \ (uq value))))
             ((uq bn) \ (begin (uq val))) ((uq en) \ (end (uq val))))
            (< (uq bn) (uq en))
            (setv (uq bn) (successor (uq bn)))
      (let (((uq name) \ (source (uq bn))))
        (uql (get-varargs-list (- (arg-count mc) 2))))))))
```

**Comment by porky11** [comment]
ok, I wrote a better version that works,
