### ISSUE TITLE
Adding read-macros for unquoting sexpressions

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#73]
in cl i liked to be able to write 
```
#+nil
(defun x …)
```
would be nice if you could add this
(when i didn't know about `#+` I defined my own read-macro for this `#;" which may also be nice here, because multiline-comments start with `#` and single-line comments with `;`. I think, I even saw this in some other lispy language)

**Comment by tomhrr** [comment]
On Thu, Sep 01, 2016 at 03:53:08AM -0700, Fabio Krapohl wrote:
> in cl i liked to be able to write 
>
> #+nil
> (defun x …)
> 
> would be nice if you could add this

I don't think it's worth adding another core form (of sorts) for
skipping the next expression.  Although having this would be
convenient, it would be the only form that operated without 'wrapping'
its arguments, which seems like an unwarranted extension of the core
syntax.  Apart from that, the alternatives (comments, potential 'skip'
macros) are not so onerous that adding a core form to avoid their use
would be appropriate.

**Comment by porky11** [comment]
Some skip macro seems like a better alternative
