### ISSUE TITLE
Big strings cause segfaults and bus errors

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#74]
If strings are larger than about 260 chars, they can't be defined as local variable

**Comment by tomhrr** [comment]
On Thu, Sep 01, 2016 at 04:39:48AM -0700, Fabio Krapohl wrote:
> If strings are larger than about 260 chars, they can't be defined as
> local variable

I'm not able to replicate this, for local variables (auto/intern) or
global variables (intern/extern).  It's possible that one of the
recent fixes has addressed this, though it seems unlikely.  Do you
have a test case?

**Comment by porky11** [comment]
I'll test it again at weekend and show some example if still not working

**Comment by porky11** [comment]
I'm not able to reproduce this error in simple examples anymore, but if I write too long shader-sources it doesn't compile anymore (just add some spaces at begin of each line here https://github.com/porky11/planets/blob/master/src/game.dt#L92)

**Comment by tomhrr** [comment]
On Sat, Sep 10, 2016 at 05:49:35AM -0700, Fabio Krapohl wrote:
> I'm not able to reproduce this error in simple examples anymore, but if I write too long shader-sources it doesn't compile anymore (just add some spaces at begin of each line here https://github.com/porky11/planets/blob/master/src/game.dt#L92)

Thanks, this has been fixed.
