### ISSUE TITLE
Error after instantiating concept macros

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#75]
I have a working program, then I instantiate some concept-macro and then this error-message appears at positions of the program, that I didn't change and don't even use `#`:
`error: cannot take address of non-lvalue`
(see using-concept-macros branch of my planets project)

**Comment by porky11** [comment]
(see using-concept-macros branch of my planets project)

**Comment by tomhrr** [comment]
On Thu, Sep 01, 2016 at 06:01:33AM -0700, Fabio Krapohl wrote:
> I have a working program, then I instantiate some concept-macro and
> then this error-message appears at positions of the program, that I
> didn't change and don't even use #:
> error: cannot take address of non-lvalue
> (see using-concept-macros branch of my planets project)

Just confirming, is this still replicable and/or a problem?

**Comment by porky11** [comment]
I wasn't able to test yet, but if you got my program working it should be ok
