### ISSUE TITLE
Creating setfable functions?

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#76]
in c++ you would return a value by reference (`&`), when you want to be able to set it.
returning by reference seems not to be possible in dale (`(fn (ref int) …)`)
will this be possible?
if not, it's no problem, I'd just write macros for my accessors

**Comment by tomhrr** [comment]
On Thu, Sep 01, 2016 at 08:05:50AM -0700, Fabio Krapohl wrote:
> in c++ you would return a value by reference (`&`), when you want to be able to set it.
> returning by reference seems not to be possible in dale (`(fn (ref int) …)`)
> will this be possible?
> if not, it's no problem, I'd just write macros for my accessors

This is only supported insofar as a function can return a pointer,
which can then be used as the first argument to setf.  I don't know of
any compelling use cases for reference return, and it would likely
require a 'proper' (more C++-like) implementation of references.
Compared with the current model, where reference parameter types act
as pointers within procedures, that would complicate things in the
language core significantly.
