### ISSUE TITLE
lvalues get cast to rvalues sometimes after macroexpansion

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#77]
This doesn't work, but it should work
```
(import macros)
(import cstdio)

(def obj (struct intern ((val (array-of 2 int)))))

(using-namespace std.macros
(def val (macro intern (obj)
  (qq : (uq obj) val)))
)

(def obj (var intern obj))

(def main (fn extern-c void (void)
  (setf (val obj) (array 1 2)) ;;works
  (printf "%i" ($ (val obj) 1)) ;;does not work, even if it works when calling it directly with the macroexpansion
  (return)))
```

**Comment by tomhrr** [comment]
Thanks, this works properly now.  In the example, '(val obj)', as well
as '(: obj val)', evaluate to pointers to int arrays, which must be
dereferenced via '@' before '$' can be used to index into them.  See
https://github.com/tomhrr/dale/blob/master/t/src/aref-problem.dt.
