### ISSUE TITLE
Don't require elements of sequences to be Comparable

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#80]
Normally those operations won't be used anyway and don't even make sence.

**Comment by tomhrr** [comment]
On Mon, Sep 05, 2016 at 12:59:55PM -0700, Fabio Krapohl wrote:
> Normally those operations won't be used anyway and don't even make
> sence.

Thanks, this has been fixed.   The containers continue to implement
EqualityComparable and LessThanComparable when the argument type
implements those concepts, too.
