### ISSUE TITLE
Add anonymous structs

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#83]
A macro like this should work, but I didn't test it:
```
(def struct (macro extern (struct-def)
  (let ((name \ (make-gensym-var)))
    (qq do
      (def (uq name)
        (struct intern (uq struct-def)))
      (q (uq name)))))
```

**Comment by tomhrr** [comment]
On Wed, Sep 07, 2016 at 10:15:26AM -0700, Fabio Krapohl wrote:
> A macro like this should work, but I didn't test it:
>
> (def struct (macro extern (struct-def)
>   (let ((name \ (make-gensym-var)))
>     (qq do
>       (def (uq name)
>         (struct intern (uq struct-def)))
>       (q (uq name)))))

Some additional work would be required to properly support anonymous
structs appearing within other structs, and it doesn't seem like a
feature that would be used so often that it should go into the core
language.  Are there use cases other than the embedding of one struct
within another?

**Comment by porky11** [comment]
I thought about implementing some closure-like objects, which could be implemented as structs, whose type depends on the number and type of arguments inside the function it is called from, (the captured variables)
Some tuple type may also be done by a macro returning an anonymous struct.
Maybe both can also be done using concepts instead
