### ISSUE TITLE
Some errors in eg/module-to-markdown/module-to-markdown.dt

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#87]
You'll see if you rebuild,
after removing something in the CMakeList.txt it compiled, and after reinserting it, it still worked, so maybe wrong dependencies declared

**Comment by tomhrr** [comment]
On Sat, Sep 10, 2016 at 12:32:26AM -0700, Fabio Krapohl wrote:
> You'll see if you rebuild,
> after removing something in the CMakeList.txt it compiled, and after reinserting it, it still worked, so maybe wrong dependencies declared

Thanks, this should be fixed now.
