### ISSUE TITLE
Operator macros doesn't work currently

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#93]
the error is `unquoting null node`, in almost every module, which means, that the versions of the macros will be called without variatic args, so the argument of uql is `(nullptr DNode)`, so the function selection is done wrong in some cases

```
(using-namespace std.macros
(def + (macro intern (a b ...)
  (qq + (+ (uq a) (uq b)) (uql (get-varargs-list (- (arg-count mc) 2))))))
)

(def new-type (struct intern ((value int))))

(def + (fn intern (retval new-type) ((a new-type) (b new-type))
  (setf (:@ retval value)  (+ (@: a value) (@: b value))))) ;;this `+` doesn't use + for ints, but the + macro, but only if this function is defined after the macro

```

**Comment by tomhrr** [comment]
On Sun, Sep 11, 2016 at 04:03:08AM -0700, Fabio Krapohl wrote:
> the error is `unquoting null node`, in almost every module, which means, that the versions of the macros will be called without variatic args, so the argument of uql is `(nullptr DNode)`, so the function selection is done wrong in some cases

Thanks, it looks like there are some cases where macros are
incorrectly being preferred to functions.  This has been fixed for
this case, but it's likely that more changes will be required.

**Comment by tomhrr** [comment]
This should be fine now.

**Comment by porky11** [comment]
another example, which does not work:
```
(import macros)

(using-namespace std.macros
  (def printf-multi (fn extern ((str (p (const char))) (val int))
    (printf str val)))
  (def printf-multi (macro extern ((str (p (const char))) val ...)
    (qq do (printf-multi (uq str) (uq val))
           (printf-multi (uq str) (uql (get-varargs-list (- (arg-count mc) 2)))))))
)

(def main (fn extern-c void (void)
  (printf-multi "%i\n" 1 2 3)))

```

**Comment by porky11** [comment]
This also seems to work now, since #106 has been fixed

**Comment by porky11** [comment]
Wait, it just works for functions defined before operator-macros is imported, so I have to ensure that all function-overloads are defined, before i use the variadic version of the operator

**Comment by porky11** [comment]
I tried it again, seems to work, even if importing it before everything else
