### ISSUE TITLE
void-functions have to return void explicitely in many cases

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#95]
When functions return void, I have to return it explicitly normally, else it shows errors for returning the wrong type.
For void-functions I don't want to think about the return-type of the last expression. It should just work.

**Comment by tomhrr** [comment]
On Tue, Sep 13, 2016 at 02:24:39AM -0700, Fabio Krapohl wrote:
> When functions return void, I have to return it explicitly normally, else it shows errors for returning the wrong type.
> For void-functions I don't want to think about the return-type of the last expression. It should just work.

Thanks, this has been fixed.
