### ISSUE TITLE
Error when parsing arrays of float

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#96]
```
(def main (fn extern-c void (void)
  (def x (var auto \ (array-of 2 float (array 0.0 0.0))))
  (return)))
;;error: expected return expression with type float (got type int instead)
```
it seems to parse the numbers in the array (0.0) as ints

**Comment by tomhrr** [comment]
On Tue, Sep 13, 2016 at 02:55:06PM -0700, Fabio Krapohl wrote:
>
> (def main (fn extern-c void (void)
>   (def x (var auto \ (array-of 2 float (array 0.0 0.0))))
>   (return)))
> ;;error: expected return expression with type float (got type int instead)
>
> it seems to parse the numbers in the array (0.0) as ints

Thanks, this has been fixed.
