### ISSUE TITLE
Special parameters of setf don't work in struct definitions

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#98]
The definitions for structs and arrays evaluate in a special way, if the type of the variable matches, but in some cases (only inside struct-definitions, I think) it is not possible, even if the type is known
```
(def X (struct intern ((value (array-of 2 int)))))

(def main (fn extern-c void (void)
  (def a (var auto (array-of 2 int) (array 1 1))) ;;possible
  (setv a (array 0 0)) ;;possible
  (def x (var auto X ((value (array 1 2))))))) ;;not possible
```
Shouldn't it work in this case too?

**Comment by tomhrr** [comment]
On Tue, Sep 13, 2016 at 03:43:09PM -0700, Fabio Krapohl wrote:
> The definitions for structs and arrays evaluate in a special way, if the type of the variable matches, but in some cases (only inside struct-definitions, I think) it is not possible, even if the type is known
> 
> (def X (struct intern ((value (array-of 2 int)))))
> 
> (def main (fn extern-c void (void)
>   (def a (var auto (array-of 2 int) (array 1 1))) ;;possible
>   (setv a (array 0 0)) ;;possible
>   (def x (var auto X ((value (array 1 2))))))) ;;not possible
>
> Shouldn't it work in this case too?

Yep, this should now work properly.
